Istanbuljs upgrade and polymer 3 support
Bubbit/wct-istanbub pull request #9
Opened 2018-05-24 12:05 UTC by Bubbit

Closes #8 & #7

2018-05-30 10:49 UTC, jimivdw requested changes

2018-05-30 10:49 UTC, jimivdw commented on lib/instrumenter.js
> +module.exports = InstrumenterIstanbul
No semi-colons?

Also, some of the functions could be shortened

2018-05-30 10:49 UTC, jimivdw commented on lib/middleware.js
> +      cache[asset] = html ? cache[asset] = scriptHook(code, { scriptCallback: instrumentScript }) : instrumenter.instrumentSync(code, path);
```
cache[asset] = html ? cache[asset] = scriptHook( ...
                      ~~~~~~~~~~~~~~~
```
Doesn't look quite right, or am I missing something here?

2018-05-30 10:49 UTC, jimivdw commented on lib/middleware.js
> +      if (absolutePath.match(/\.js?$/)) {
Is the `s` optional on purpose?

2018-05-30 10:49 UTC, jimivdw commented on lib/middleware.js
> +        return res.send(html.replace('coverage = global[gcv] || (global[gcv] = {});', 'coverage = global.WCT.share.__coverage__ || (global.WCT = { share: { __coverage__: {} } }); '));
Since it's here twice now, I would extract this replace thing.

Also, did you consider filing an issue with IstanbulJS for this?

2018-05-30 10:49 UTC, jimivdw commented on lib/util.js
> + * Taken from: https://github.com/Polymer/web-component-tester/blob/master/runner/config.ts
Any reason not to simply import this file and use the function straight from wct?

2018-05-30 10:49 UTC, jimivdw commented on lib/middleware.js
> +      if (absolutePath.match(/\.js?$/)) {
You could also consider adding the (less common) `.es` extension here

2018-05-30 10:49 UTC, jimivdw commented on lib/middleware.js
> +      return next();
Technically the instrument debug log is still emitted, even though the code has not been instrumented. Maybe make a distinction for that?

2018-05-30 13:00 UTC, Bubbit commented on lib/util.js
> + * Taken from: https://github.com/Polymer/web-component-tester/blob/master/runner/config.ts
It was used somewhere else before as well, and it's a private function.

Now I have replaced it, it does increase the node_modules folder size purely for wct-istanbub a lot, but I guess considering you have web-component-tester anyway it shouldn't matter

2018-05-30 13:01 UTC, Bubbit commented on lib/middleware.js
> +        return res.send(html.replace('coverage = global[gcv] || (global[gcv] = {});', 'coverage = global.WCT.share.__coverage__ || (global.WCT = { share: { __coverage__: {} } }); '));
I did consider, but didn't do it yet

2018-05-30 13:10 UTC, Bubbit commented on lib/util.js
> + * Taken from: https://github.com/Polymer/web-component-tester/blob/master/runner/config.ts
On a second viewing, I did add the functionality of the root is not set to fallback to process.cwd() which web-component-tester has somewhere else in the chain. (which is why all the tests fail if I remove it ;))

2018-05-31 08:55 UTC, jimivdw approved these changes

2018-06-06 15:51 UTC, jimivdw commented
lgtm

2018-06-07 05:44 UTC, merged